ga:
  population_size: 100
  n_generations: 40
  crossover_prob: 0.5581051326502489
  mutation_prob: 0.2827567587790135
  tournament_size: 2
  elitism_ratio: 0.12
  mutation_types:
    threshold_perturbation: 0.45
    feature_replacement: 0.25
    prune_subtree: 0.25
    expand_leaf: 0.05
tree:
  max_depth: 7
  min_samples_split: 8
  min_samples_leaf: 3
fitness:
  mode: weighted_sum
  weights:
    accuracy: 0.8022045373796255
    interpretability: 0.1977954626203745
  interpretability_weights:
    node_complexity: 0.49990019634924365
    feature_coherence: 0.1
    tree_balance: 0.1
    semantic_coherence: 0.3
experiment:
  datasets:
    - iris
    - wine
    - breast_cancer
  cv_folds: 20
  random_state: 42

optimization:
  study_name: ga_opt_breast_cancer_20260226_111520
  n_trials: 30
  best_value: 0.9420431609998449
  best_trial_number: 23
  optimization_date: '2026-02-26T11:21:02.376365'
